config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'conversions#index'

  resources :conversions, except: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversion.rb
# app/models/conversion.rb
# rubocop:disable Style/RedundantSelf
class Conversion < ApplicationRecord
  # associations
  belongs_to :currency
  belongs_to :to, class_name: "Currency"

  # validations
  # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :to_id, uniqueness: { scope: :currency_id }
  # rubocop:enable Rails/UniqueValidationWithoutIndex
  validate :currency_equal_to_to

  # scopes
  default_scope { order(created_at: :desc) }

  # callbacks
  after_create_commit do
    broadcast_prepend_to 'conversions'
  end

  after_update_commit do
    broadcast_replace_to 'conversions'
  end

  after_destroy_commit do
    broadcast_remove_to 'conversions', target: "conversion_#{self.id}"
  end

  def currency_equal_to_to
    errors.add(:to, "equal to from") if currency == to && !to.nil?
  end
end
# rubocop:enable Style/RedundantSelf

app/models/currency.rb
# app/models/currency.rb
# rubocop:disable Style/RedundantSelf
class Currency < ApplicationRecord
  # validations
  validates :iso_code, presence: true, uniqueness: { case_sensitive: false }
  validates :rate, presence: true

  # scopes
  scope :base, -> { find_by(is_base: true) }

  # associations
  has_many :conversions, dependent: :destroy

  # callbacks
  after_update_commit do
    con = Conversion.arel_table
    Conversion.where(con[:currency_id].eq(self.id).or(con[:to_id].eq(self.id))).find_each(&:save)
  end

  def rate_of_base
    Currency.base.rate / self.rate
  end

  def rate_of_to(to)
    format("%5f", (self.rate_of_base / to.rate_of_base))
  end
end
# rubocop:enable Style/RedundantSelf

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversions_controller.rb
# app/controllers/conversions_controller.rb
class ConversionsController < ApplicationController
  before_action :get_conversations, only: [:new, :index, :create]
  before_action :set_conversion, only: [:destroy]

  def index; end

  def new
    @conversion = Conversion.new
  end

  def create
    @conversion = Conversion.new(conversion_params)

    if @conversion.save
      flash[:notice] = "Conversion was successfully created."
      redirect_to new_conversion_path
    else
      render :new
    end
  end

  def destroy
    @conversion.destroy

    flash[:notice] = "Conversion was successfully destroyed."
    redirect_to new_conversion_path
  end

  private

  def conversion_params
    params.require(:conversion).permit(:currency_id, :to_id)
  end

  # rubocop:disable Naming/AccessorMethodName
  def get_conversations
    @conversions = Conversion.page(params[:page])
  end
  # rubocop:enable Naming/AccessorMethodName

  def set_conversion
    @conversion = Conversion.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversions/_conversion.slim
= turbo_frame_tag dom_id(conversion) do
  .row
    .col-4.text-center #{conversion.currency.iso_code}
    .col-4.text-center #{conversion.to.iso_code}
    .col-4.text-center #{conversion.currency.rate_of_to(conversion.to)}

app/views/conversions/_form.slim
= simple_form_for model, id: dom_id(model), html: { data: { turbo: "false"}} do |f|
  = render "shared/errors", model: model
  .mb-3
    = f.input :currency_id, collection: Currency.all, value_method: :id, label_method: :iso_code, prompt: "Select a currency", label: "From"
  .mb-3
    = f.input :to_id, collection: Currency.all, value_method: :id, label_method: :iso_code, prompt: "Select a currency", label: "To"
  .mb-3
    = f.submit class: "btn btn-success"

app/views/conversions/index.slim
h1.fw-bold.mb-5 Conversions

= turbo_stream_from "conversions"

= turbo_frame_tag "conversions" do
  .d-flex.conversions-table
    .row.conversions-row.shadow
      .col-4.tab From
      .col-4.tab To
      .col-4.tab Rate
      = render @conversions
= paginate @conversions

app/views/conversions/new.slim
h1 Create a new currency conversion
= render "form", model: @conversion

table.table.table-striped
  thead
    tr
      th(scope='col') From
      th(scope='col') To
      th(scope='col') Rate
      th(scope='col') Action
  tbody
    - @conversions.each do |conversion|
      tr
        td #{conversion.currency.iso_code}
        td #{conversion.to.iso_code}
        td #{conversion.currency.rate_of_to(conversion.to)}
        td
          = button_to conversion_path(conversion), method: :delete, form: { data: { turbo: "false"} }, class: "btn btn-sm btn-danger"
            = icon "fas", "trash", class: "text-white"
            |&nbsp;Delete
= paginate @conversions

app/views/layouts/application.slim
doctype html
html.h-100
  head
    title Rails Currency Conversion
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body.d-flex.flex-column.h-100
    header
      nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
        .container-fluid
          = link_to "RAILS CURRENCY CONVERSION", root_path, class: "navbar-brand"
          button.navbar-toggler(type='button' data-bs-toggle='collapse' data-bs-target='#navbarCollapse' aria-controls='navbarCollapse' aria-expanded='false' aria-label='Toggle navigation')
            span.navbar-toggler-icon
          #navbarCollapse.collapse.navbar-collapse
            ul.navbar-nav.me-auto.mb-2.mb-md-0
              li.nav-item
                = active_link_to "Home", root_path, active: :exclusive, class: "nav-link"
              li.nav-item
                = active_link_to "New Conversion", new_conversion_path, active: :exclusive, class: "nav-link"
    main.flex-shrink-0
      .container.mt-5
        = render "shared/flash"
        .mt-2
          = yield
    footer.footer.mt-auto.py-3.bg-light
      .container
        span.text-muted Rails Currency Conversion | #{DateTime.now.year}

app/views/shared/_errors.slim
- if model.errors.any?
  .alert.alert-danger
    h5.alert-heading #{pluralize(model.errors.count, "error")} prohibited this #{model.class} from being saved:
    - model.errors.full_messages.each do |error|
      li #{error}

app/views/shared/_flash.slim
- flash.each do |type, message|
  .alert.alert-dismissible.fade.show(role='alert' class="#{type.eql?('notice') ? 'alert-success' : 'alert-warning'}")
    p #{message}
    button.btn-close(type='button' data-bs-dismiss='alert' aria-label='Close')